#+TAGS: CIL


* How to Exploit Hyperspherical Embeddings for Out-of-Distribution Detection?
** Review
*** Info
- *Arxiv:* https://arxiv.org/abs/2203.04450
- *Authors:* Yifei Ming, Yiyou Sun, Ousmane Dia, Yixuan Li
- *Date:* Mar 2022
*** Problem Being Solved?
Out Of Distribution Detectin (OOD) is a important (described in [[./continual-learning-theoretical.org]]). The paper tries to create better OOD detection by modeling the outputs of a CIL model onto a hyperspherical space. Then, using two loss function (create tight clusters and distribute those clusters away from each other) they create a representation that allows for better OOD.
*** What is an overview of the method?
The representative samples are modeled using a von Misis-Fisher (vMF) distribution which basically just a spherical gaussian distribution with unit norms. Then, these representative samples are
*** What are the metrics of success?
*** What are the key innovations over prior work?
*** What are the key results?
*** How might this work have long term impact?
** Questions
